//
// Created by raffa on 12/01/2026.
//

#ifndef SASSARO_MANIGLIOEILPIUBELLODELMONDO_ESERCIZIOOTTO_H
#define SASSARO_MANIGLIOEILPIUBELLODELMONDO_ESERCIZIOOTTO_H
void EsercizioOtto();
#endif //SASSARO_MANIGLIOEILPIUBELLODELMONDO_ESERCIZIOOTTO_H