//
// Created by raffa on 12/01/2026.
//

#ifndef SASSARO_MANIGLIOEILPIUBELLODELMONDO_ESERCIZIOSETTE_H
#define SASSARO_MANIGLIOEILPIUBELLODELMONDO_ESERCIZIOSETTE_H
void EsercizioSette();
#endif //SASSARO_MANIGLIOEILPIUBELLODELMONDO_ESERCIZIOSETTE_H