//
// Created by raffa on 12/01/2026.
//

#ifndef SASSARO_MANIGLIOEILPIUBELLODELMONDO_ESERCIZIOTRE_H
#define SASSARO_MANIGLIOEILPIUBELLODELMONDO_ESERCIZIOTRE_H

void EsercizioTre(int *a,  int *b);

#endif //SASSARO_MANIGLIOEILPIUBELLODELMONDO_ESERCIZIOTRE_H