//
// Created by raffa on 12/01/2026.
//

#ifndef SASSARO_MANIGLIOEILPIUBELLODELMONDO_ESERCIZIOUNO_H
#define SASSARO_MANIGLIOEILPIUBELLODELMONDO_ESERCIZIOUNO_H

void EsercizioUno(int a, int b, int* quoziente, int* resto);

#endif //SASSARO_MANIGLIOEILPIUBELLODELMONDO_ESERCIZIOUNO_H