//
// Created by raffa on 12/01/2026.
//

#ifndef SASSARO_MANIGLIOEILPIUBELLODELMONDO_ESERCIZIOQUATTRO_H
#define SASSARO_MANIGLIOEILPIUBELLODELMONDO_ESERCIZIOQUATTRO_H

int EsercizioQuattro(void);

#endif //SASSARO_MANIGLIOEILPIUBELLODELMONDO_ESERCIZIOQUATTRO_H