//
// Created by raffa on 12/01/2026.
//

#ifndef SASSARO_MANIGLIOEILPIUBELLODELMONDO_ESERCIZIOSEI_H
#define SASSARO_MANIGLIOEILPIUBELLODELMONDO_ESERCIZIOSEI_H

void EsercizioSei();

#endif //SASSARO_MANIGLIOEILPIUBELLODELMONDO_ESERCIZIOSEI_H